### PR TITLE
fix #68, add input blocking

### LINKED ISSUE #68: make it so that when you respawn, you have to start pressing move again to move
cos when you die, and you're still holding a key, then you start moving and the timer starts as soon as you start

### PR DESCRIPTION
**Pull request by circles-png**

### CODE REVIEW

**Comment by angusmason** [comment]
whys this not appearing in vscode

**Comment by angusmason** [comment]
nevermind

**Comment by angusmason** [comment]
where did coyote time which isnt actually coyote time go

**Comment by angusmason** [comment]
it does mean that you can't triple jump, but it also means it doesn't feel as nice....have to find a good amount of coyote time

**Comment by circles-png** [comment]
what is your definition of coyote time

**Comment by circles-png** [comment]
> where did coyote time which isnt actually coyote time go

it did nothing (you can go back and see)

**Review by angusmason — APPROVED** [review]
approved

**Pull request merged**
